default_language_version:
  python: python3

exclude: ^(data|logs)

ci:
  autoupdate_schedule: monthly
  autoupdate_commit_msg: autoupdate pre-commit hooks
  autofix_commit_msg: autofix pre-commit hooks

repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^src/models/layers/geo_conv\.py$
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.2
    hooks:
      - id: uv-export
        args: [--quiet]
      - id: pip-compile
        args: [pyproject.toml, --no-annotate, --no-header, -o, requirements.txt, --quiet]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        exclude: ^src/models/layers/geo_conv\.py$

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
          - mdformat-ruff

  - repo: https://github.com/crate-ci/typos
    rev: v1.44.0
    hooks:
      - id: typos
        exclude: (^src/utils/data\.py$|\.ipynb$)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: ["--line-length=99", "--ignore=I001"]
      - id: nbqa-isort
        args: ["--profile=black"]
