[project]
name = "lightning-cegann2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "freud-analysis>=3.4.0",
    "ipywidgets>=8.1.8",
    "lightning>=2.4.0",
    "ovito>=3.15.0",
    "pandas>=2.2.3",
    "tensorboard>=2.18.0",
    "torch-geometric>=2.6.1",
]

[dependency-groups]
api = ["mp-api>=0.44.0", "kaggle>=1.6.17", "python-dotenv>=1.0.1"]
optuna = [
    "optuna>=4.1.0",
    "optuna-integration>=4.2.1",
    "optuna-dashboard>=0.20.0",
    "rich>=13.9.4",
    "scikit-learn>=1.6.1",
    "optunahub>=0.4.0",
    "cmaes>=0.12.0",
    "scipy>=1.15.3",
    "fvcore>=0.1.5.post20221221",
]
dev = [
    "ipykernel>=6.29.5",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
    "line-profiler>=5.0.0",
]

[tool.ruff]
src = ["src"]
line-length = 99
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = [
    "F",   # flake8 rules
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8 naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    # "S", # flake8-bandit
    "BLE", # flake8-blind-except
    # "FBT", # flake8-boolean-trap
    "PERF", # flake8-perf

]
ignore = [
    "N812",   # lowercase imported as non lowercase
    "D100",   # missing docstring in public module
    "D104",   # missing docstring in public package
    "D105",   # missing docstring in magic method
    "D107",   # missing docstring in __init__
    "D205",   # 1 blank line required between summary line and description
    "ANN002", # missing type annotation for *args
    "ANN003", # missing type annotation for **kwargs
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # Unused import
"tests/**" = [
    "D",   # Pydocstyle
    "ANN", # flake8-annotations
]
"notebooks/**" = [
    "D",   # Pydocstyle
    "ANN", # flake8-annotations
]
"scripts/**" = [
    "D",   # Pydocstyle
    "ANN", # flake8-annotations
]
"src/module.py" = ["D102"] # Missing docstring in public method

[tool.mypy]
exclude = "^scripts/.*\\.py$"
