lr: 0.004855745492302062
warmup: 200
max_iters: -1  # Will be calculated automatically in main.py
compile: true
gradient_clip_val: 1.0
gradient_clip_algorithm: norm

model:
  class_path: src.models.PaiNN
  init_args:
    hidden_channels: 64
    num_layers: 4
    num_radial: 4
    dropout: 0.1

metrics:
  - class_path: torchmetrics.F1Score
  - class_path: torchmetrics.AUROC
  - class_path: torchmetrics.Accuracy
  - class_path: torchmetrics.ConfusionMatrix
