search_type: local              # <default “local”>  For the type of search
neighbors: 12                   # <default 12>       Number of nearest neighbors for graph construction
rcut: 7.5                       # <default 3>        Initial cutoff for finding neighbors
search_delta: 1                 # <default 1>        Increment in rcut for finding nearest neighbors
n_classes: 4                    # <default 2>        Number of classfication classes
train_size: null                # <default None>     Size of training data
test_size: null                 # <default None>     Size of test data
val_size: null                  # <default None>     Size of validation data
train_ratio: 0.8                # <default 0.8>      Training ratio
val_ratio: 0.1                  # <default 0.1>      Validation ratio
test_ratio: 0.1                 # <default 0.1>      test ratio
return_test: true               # <default False>    Whether to return test loader or not
num_workers: 6                  # <default 1>        Data loader option
pin_memory: false               # <default False>    Data loader option
bond_fea_len: 80                #! <default 80>       Size of edge feature vector
angle_fea_len: 80               #! <default 80>       Size of the angle feaure vector
n_conv_edge: 2                  #! <default 3>        number of edge convolution
h_fea_edge: 128                 #! <default 128>      Hiden features for edge dense layer output
h_fea_angle: 128                #! <default 128>      Hiden features for angle dense layer output
embedding: false                # <default False>    Whether the predict the embeddings of the strutures or not
epochs: 100                     #! <default 100>      number epochs
batch_size: 64                  #! <default 64>       Data loader option
optimizer: adam                 # <default "adam">   optimizer option
weight_decay: 0                 # <default 0>        optimizer option
momentum: 0.9                   # <default 0.9>      optimizer option
learning_rate: 0.01             # <default 1e-2>     optimizer option
scheduler: true                 # <default True>     using a step learning rate reduction
gamma: 0.1                      # <default 0.1>      scheduler option
step_size: 30                   # <default 30>       scheduler option
resume: false                   # <default False>    To resume search
write_checkpoint: true          # <default True>     Whether to write checkpoint or not
checkpoint_every: 10            # <default 1>        Write checkpoint after this many epochs
progress: true                  # <default True>     Show progress bar