angle_fea_len: 80
batch_size: 64
bond_fea_len: 80
checkpoint_every: 20
embedding: false
epochs: 3
gamma: 0.5
h_fea_angle: 256
h_fea_edge: 256
learning_rate: 0.01
n_classes: 3
n_conv_edge: 2
neighbors: 12
num_workers: 1
pin_memory: true
rcut: 4
resume: false
search_delta: 1
search_type: local
step_size: 100
test_ratio: 0.0
train_ratio: 0.8
val_ratio: 0.2
progress: true
